# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  name: suchait-consulting-pool

steps:

- task: Gradle@3
  inputs:
    gradleWrapperFile: './gradlew'
    workingDirectory: '$(Build.SourcesDirectory)'
    tasks: 'clean build'
    publishJUnitResults: false
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

  
- task: Docker@2
  inputs:
    containerRegistry: 'retailsolution01'
    repository: 'urbanimages/user-service'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: '(Build.BuildId)'