spring:
  profiles:
    active: local
  application:
    name: user-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    default-schema: RETAIL_DB
    locations:
      - classpath:db/migration

server:
  port: 8081

