apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  url: amRiYzpwb3N0Z3Jlc3FsOi8vbXktcmVsZWFzZS1wb3N0Z3Jlc3FsLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9yZXRhaWxfZGI=
  username: cG9zdGdyZXM=
  password: RXRQR2JYcE9aWQ==
